config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :desks

  root 'welcome#welcome'

  get 'reservations' => 'reservations#index'

end

app/models/desk.rb
class Desk < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/desks_controller.rb
class DesksController < ApplicationController
  before_action :set_desk, only: [:show, :edit, :update, :destroy]

  # GET /desks
  # GET /desks.json
  def index
    @desks = Desk.all
  end

  # GET /desks/1
  # GET /desks/1.json
  def show
  end

  # GET /desks/new
  def new
    @desk = Desk.new
  end

  # GET /desks/1/edit
  def edit
  end

  # POST /desks
  # POST /desks.json
  def create
    @desk = Desk.new(desk_params)

    respond_to do |format|
      if @desk.save
        format.html { redirect_to @desk, notice: 'Desk was successfully created.' }
        format.json { render :show, status: :created, location: @desk }
      else
        format.html { render :new }
        format.json { render json: @desk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /desks/1
  # PATCH/PUT /desks/1.json
  def update
    respond_to do |format|
      if @desk.update(desk_params)
        format.html { redirect_to @desk, notice: 'Desk was successfully updated.' }
        format.json { render :show, status: :ok, location: @desk }
      else
        format.html { render :edit }
        format.json { render json: @desk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /desks/1
  # DELETE /desks/1.json
  def destroy
    @desk.destroy
    respond_to do |format|
      format.html { redirect_to desks_url, notice: 'Desk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_desk
      @desk = Desk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def desk_params
      params.fetch(:desk, {})
    end
end

app/controllers/reservations_controller.rb
require 'oj'
require "uri"
require "net/http"

class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :destroy]
  after_action :call_button, only: [:update]
  skip_before_action :verify_authenticity_token, only: [:create, :update]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all  
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    if(params['data'])
        reservation_hash = Oj.load(params['data']);      
        @reservation = Reservation.new(device_id: reservation_hash["deviceId"], reservation_am: reservation_hash["reservation_am"], reservation_pm: reservation_hash["reservation_pm"])
        #@reservation = Reservation.new(reservation_hash)
    else
        @reservation = Reservation.new(reservation_params)
    end 
  

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if !@reservation && params['data']
            reservation_hash = Oj.load(params['data'])
            @reservation = Reservation.find(reservation_hash["id"])
            if @reservation.update(device_id: reservation_hash["deviceId"], reservation_am: reservation_hash["reservation_am"], reservation_pm: reservation_hash["reservation_pm"])
              format.json { render :show, status: :ok, location: @reservation }
            end         
      else 
        set_reservation               
        if @reservation.update(reservation_params)
          format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
          format.json { render :show, status: :ok, location: @reservation }
        else
          format.html { render :edit }
          format.json { render json: @reservation.errors, status: :unprocessable_entity }
        end
      end
    end      
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  # POST on button device to update leds
  def call_button
    if @reservation && @reservation.device_id
      reqstArg = if @reservation.reservation_am  && !@reservation.reservation_pm
        "am"
      elsif @reservation.reservation_pm && !@reservation.reservation_am
        "pm"
      elsif @reservation.reservation_am && @reservation.reservation_pm
        "ampm"
      end
      ##calling function to udpate leds
      Net::HTTP.post_form(URI.parse('https://api.particle.io/v1/devices/'+@reservation.device_id+'/setBtnLeds'),'access_token'=>'4b481cdd6ca24ffdd5ee6e4adb78c4dc61cc88fa', 'arg'=> reqstArg)  
    end 
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:desk_id, :description, :reservation_date, :reservation_pm, :reservation_am, :event, :data, :published_at, :coreid)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desks_helper.rb
module DesksHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/desks/_form.html.erb
<%= form_for(@desk) do |f| %>
  <% if @desk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@desk.errors.count, "error") %> prohibited this desk from being saved:</h2>

      <ul>
      <% @desk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/desks/edit.html.erb
<h1>Editing Desk</h1>

<%= render 'form' %>

<%= link_to 'Show', @desk %> |
<%= link_to 'Back', desks_path %>

app/views/desks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Desks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @desks.each do |desk| %>
      <tr>
        <td><%= link_to 'Show', desk %></td>
        <td><%= link_to 'Edit', edit_desk_path(desk) %></td>
        <td><%= link_to 'Destroy', desk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Desk', new_desk_path %>

app/views/desks/new.html.erb
<h1>New Desk</h1>

<%= render 'form' %>

<%= link_to 'Back', desks_path %>

app/views/desks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_desk_path(@desk) %> |
<%= link_to 'Back', desks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReservationSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
<div class="container-fluid">
<div class="navbar-header">
<button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<div class="collapse navbar-collapse">
<ul class="nav navbar-nav">
<li><a href="/agenda/index">Faire une réservation</a></li>
<li><a href="/instant/form">Réservation immédiate</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
<li class="dropdown">
  <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">
  Administration
  <span class="caret"></span>
  </a>
    <ul class="dropdown-menu">
      <li><a href="/entities">Entités</a></li>
      <li><a href="/zones">Zones</a></li>
      <li><a href="/places">Emplacements</a></li>
      <li><a href="/typo_places">Typologies</a></li>
      <li><a href="/users">Utilisateurs</a></li>
    </ul>
</li>
<li class="dropdown">
    <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">
    Fabrice BERNARD
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
  <li><a href="/">Mon tableau de bord</a></li>
  <li class="divider" role="separator"></li>
  <li><a href="/accueil/faq">Aide</a></li>
  <li class="divider" role="separator"></li>
  <li><a href="/entities">Mes entités</a></li>
  <li><a href="/places/54">Mon bureau</a></li>
  <li class="divider" role="separator"></li>
  <li><a href="/stats/index">Statistiques</a></li>
  <li class="divider" role="separator"></li>
  <li><a href="/session/logout">Quitter</a></li>
  </ul>
  </li>
  </ul>
  </div>
  </div>
  </nav>
<div class="container-fluid">
  <%= yield %>
</div>


</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desk_id %><br>
    <%= f.number_field :desk_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :reservation_date %><br>
    <%= f.date_select :reservation_date %>
  </div>
  <div class="field">
    <%= f.label :reservation_pm %><br>
    <%= f.check_box :reservation_pm %>
  </div>
  <div class="field">
    <%= f.label :reservation_am %><br>
    <%= f.check_box :reservation_am %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<div class="well">
<h1>Liste des réservations</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Desk</th>
      <th>Identifiant de l'appareil</th>
      <th>Description</th>
      <th>Reservation date</th>
      <th>Reservation pm</th>
      <th>Reservation am</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.desk_id %></td>
        <td><%= reservation.device_id %></td>
        <td><%= reservation.description %></td>
        <td><%= reservation.reservation_date %></td>
        <td><%= reservation.reservation_pm %></td>
        <td><%= reservation.reservation_am %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Desk:</strong>
  <%= @reservation.desk_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @reservation.description %>
</p>
<p>
  <strong>Reservation date:</strong>
  <%= @reservation.reservation_date %>
</p>

<p>
  <strong>Reservation pm:</strong>
  <%= @reservation.reservation_pm %>
</p>

<p>
  <strong>Reservation am:</strong>
  <%= @reservation.reservation_am %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/welcome/welcome.html.erb
<h2>Welcome on poc server</h2>
<p>
  The time is now: <%= Time.now %>
</p>